spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
    ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/cars
    username: postgres
    password: root
  batch:
    initialize-schema: always
    job:
      enabled: false
db-file:
  path: C:\\Users\\Tyman\\Documents\\Database Files\\
